### ISSUE TITLE
Cross compilation

### ISSUE THREAD

**Issue by jwinarske** [imagemin/gifsicle-bin#139]
What is the expected method for cross compiling?

Snippet from install.js
```
const config = [
	'./configure --disable-gifview --disable-gifdiff',
	`--prefix="${bin.dest()}" --bindir="${bin.dest()}"`
].join(' ');

try {
	await binBuild.file(path.resolve(__dirname, '../vendor/source/gifsicle-1.92.tar.gz'), [
		'autoreconf -ivf',
		config,
		'make install'
	]);
```

It cross compiles as desired if I add `--host=${TARGET_SYS}` to config.

Using `export ac_cv_build="${TARGET_SYS}"` has no impact.

### References
https://www.gnu.org/software/autoconf/manual/autoconf-2.68/html_node/Specifying-Target-Triplets.html
https://elinux.org/images/4/43/Petazzoni.pdf

**Comment by jwinarske** [comment]
This is the dramatic error when `--host` is not set when trying to cross compile.

```
| > gifsicle@5.1.0 postinstall /__w/meta-flutter/rpi4-drm-dunfell-latest/raspberrypi4-64/tmp/work/aarch64-poky-linux/webthings-gateway/1.0.0+gitAUTOINC+4c600fc973-r0/git/node_modules/gifsicle
[13672](https://github.com/meta-flutter/meta-flutter/runs/6017384947?check_suite_focus=true#step:10:13672)
| > node lib/install.js
[13673](https://github.com/meta-flutter/meta-flutter/runs/6017384947?check_suite_focus=true#step:10:13673)
| 
[13674](https://github.com/meta-flutter/meta-flutter/runs/6017384947?check_suite_focus=true#step:10:13674)
|   ⚠ Response code 404 (Not Found)
[13675](https://github.com/meta-flutter/meta-flutter/runs/6017384947?check_suite_focus=true#step:10:13675)
|   ⚠ gifsicle pre-build test failed
[13676](https://github.com/meta-flutter/meta-flutter/runs/6017384947?check_suite_focus=true#step:10:13676)
|   ℹ compiling from source
[13677](https://github.com/meta-flutter/meta-flutter/runs/6017384947?check_suite_focus=true#step:10:13677)
|   ✖ Error: Command failed: /bin/sh -c ./configure --disable-gifview --disable-gifdiff --prefix="/__w/meta-flutter/rpi4-drm-dunfell-latest/raspberrypi4-64/tmp/work/aarch64-poky-linux/webthings-gateway/1.0.0+gitAUTOINC+4c600fc973-r0/git/node_modules/gifsicle/vendor" --bindir="/__w/meta-flutter/rpi4-drm-dunfell-latest/raspberrypi4-64/tmp/work/aarch64-poky-linux/webthings-gateway/1.0.0+gitAUTOINC+4c600fc973-r0/git/node_modules/gifsicle/vendor"
[13678](https://github.com/meta-flutter/meta-flutter/runs/6017384947?check_suite_focus=true#step:10:13678)
| configure: error: in `/tmp/21d12b6b-886b-4cb7-acb0-0602085820cd':
[13679](https://github.com/meta-flutter/meta-flutter/runs/6017384947?check_suite_focus=true#step:10:13679)
| configure: error: cannot run C compiled programs.
[13680](https://github.com/meta-flutter/meta-flutter/runs/6017384947?check_suite_focus=true#step:10:13680)
| If you meant to cross compile, use `--host'.
[13681](https://github.com/meta-flutter/meta-flutter/runs/6017384947?check_suite_focus=true#step:10:13681)
| See `config.log' for more details
[13682](https://github.com/meta-flutter/meta-flutter/runs/6017384947?check_suite_focus=true#step:10:13682)
| 
[13683](https://github.com/meta-flutter/meta-flutter/runs/6017384947?check_suite_focus=true#step:10:13683)
| checking for a BSD-compatible install... /__w/meta-flutter/rpi4-drm-dunfell-latest/raspberrypi4-64/tmp/hosttools/install -c
[13684](https://github.com/meta-flutter/meta-flutter/runs/6017384947?check_suite_focus=true#step:10:13684)
| checking whether build environment is sane... yes
[13685](https://github.com/meta-flutter/meta-flutter/runs/6017384947?check_suite_focus=true#step:10:13685)
| checking for a thread-safe mkdir -p... /__w/meta-flutter/rpi4-drm-dunfell-latest/raspberrypi4-64/tmp/hosttools/mkdir -p
[13686](https://github.com/meta-flutter/meta-flutter/runs/6017384947?check_suite_focus=true#step:10:13686)
| checking for gawk... gawk
[13687](https://github.com/meta-flutter/meta-flutter/runs/6017384947?check_suite_focus=true#step:10:13687)
| checking whether make sets $(MAKE)... yes
[13688](https://github.com/meta-flutter/meta-flutter/runs/6017384947?check_suite_focus=true#step:10:13688)
| checking whether make supports nested variables... yes
[13689](https://github.com/meta-flutter/meta-flutter/runs/6017384947?check_suite_focus=true#step:10:13689)
| checking whether make sets $(MAKE)... (cached) yes
[13690](https://github.com/meta-flutter/meta-flutter/runs/6017384947?check_suite_focus=true#step:10:13690)
| checking for gcc... aarch64-poky-linux-gcc  -mcpu=cortex-a72+crc+crypto -fstack-protector-strong  -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security --sysroot=/__w/meta-flutter/rpi4-drm-dunfell-latest/raspberrypi4-64/tmp/work/aarch64-poky-linux/webthings-gateway/1.0.0+gitAUTOINC+4c600fc973-r0/recipe-sysroot
[13691](https://github.com/meta-flutter/meta-flutter/runs/6017384947?check_suite_focus=true#step:10:13691)
| checking whether the C compiler works... yes
[13692](https://github.com/meta-flutter/meta-flutter/runs/6017384947?check_suite_focus=true#step:10:13692)
| checking for C compiler default output file name... a.out
[13693](https://github.com/meta-flutter/meta-flutter/runs/6017384947?check_suite_focus=true#step:10:13693)
| checking for suffix of executables...
[13694](https://github.com/meta-flutter/meta-flutter/runs/6017384947?check_suite_focus=true#step:10:13694)
| checking whether we are cross compiling...
[13695](https://github.com/meta-flutter/meta-flutter/runs/6017384947?check_suite_focus=true#step:10:13695)
|     at /__w/meta-flutter/rpi4-drm-dunfell-latest/raspberrypi4-64/tmp/work/aarch64-poky-linux/webthings-gateway/1.0.0+gitAUTOINC+4c600fc973-r0/git/node_modules/bin-build/node_modules/execa/index.js:231:11
[13696](https://github.com/meta-flutter/meta-flutter/runs/6017384947?check_suite_focus=true#step:10:13696)
|     at processTicksAndRejections (internal/process/task_queues.js:97:5)
[13697](https://github.com/meta-flutter/meta-flutter/runs/6017384947?check_suite_focus=true#step:10:13697)
|     at async Promise.all (index 0)
[13698](https://github.com/meta-flutter/meta-flutter/runs/6017384947?check_suite_focus=true#step:10:13698)
| npm verb lifecycle gifsicle@5.1.0~postinstall: unsafe-perm in lifecycle true
[13699](https://github.com/meta-flutter/meta-flutter/runs/6017384947?check_suite_focus=true#step:10:13699)
| npm verb lifecycle gifsicle@5.1.0~postinstall: PATH: /__w/meta-flutter/rpi4-drm-dunfell-latest/raspberrypi4-64/tmp/work/aarch64-poky-linux/webthings-gateway/1.0.0+gitAUTOINC+4c600fc973-r0/recipe-sysroot-native/usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/__w/meta-flutter/rpi4-drm-dunfell-latest/raspberrypi4-64/tmp/work/aarch64-poky-linux/webthings-gateway/1.0.0+gitAUTOINC+4c600fc973-r0/git/node_modules/gifsicle/node_modules/.bin:/__w/meta-flutter/rpi4-drm-dunfell-latest/raspberrypi4-64/tmp/work/aarch64-poky-linux/webthings-gateway/1.0.0+gitAUTOINC+4c600fc973-r0/git/node_modules/.bin:/__w/meta-flutter/rpi4-drm-dunfell-latest/raspberrypi4-64/tmp/sysroots-uninative/x86_64-linux/usr/bin:/__w/meta-flutter/rpi4-drm-dunfell-latest/sources/poky/scripts:/__w/meta-flutter/rpi4-drm-dunfell-latest/raspberrypi4-64/tmp/work/aarch64-poky-linux/webthings-gateway/1.0.0+gitAUTOINC+4c600fc973-r0/recipe-sysroot-native/usr/bin/aarch64-poky-linux:/__w/meta-flutter/rpi4-drm-dunfell-latest/raspberrypi4-64/tmp/work/aarch64-poky-linux/webthings-gateway/1.0.0+gitAUTOINC+4c600fc973-r0/recipe-sysroot/usr/bin/crossscripts:/__w/meta-flutter/rpi4-drm-dunfell-latest/raspberrypi4-64/tmp/work/aarch64-poky-linux/webthings-gateway/1.0.0+gitAUTOINC+4c600fc973-r0/recipe-sysroot-native/usr/sbin:/__w/meta-flutter/rpi4-drm-dunfell-latest/raspberrypi4-64/tmp/work/aarch64-poky-linux/webthings-gateway/1.0.0+gitAUTOINC+4c600fc973-r0/recipe-sysroot-native/usr/bin:/__w/meta-flutter/rpi4-drm-dunfell-latest/raspberrypi4-64/tmp/work/aarch64-poky-linux/webthings-gateway/1.0.0+gitAUTOINC+4c600fc973-r0/recipe-sysroot-native/sbin:/__w/meta-flutter/rpi4-drm-dunfell-latest/raspberrypi4-64/tmp/work/aarch64-poky-linux/webthings-gateway/1.0.0+gitAUTOINC+4c600fc973-r0/recipe-sysroot-native/bin:/__w/meta-flutter/rpi4-drm-dunfell-latest/sources/poky/bitbake/bin:/__w/meta-flutter/rpi4-drm-dunfell-latest/raspberrypi4-64/tmp/hosttools
[13700](https://github.com/meta-flutter/meta-flutter/runs/6017384947?check_suite_focus=true#step:10:13700)
| npm verb lifecycle gifsicle@5.1.0~postinstall: CWD: /__w/meta-flutter/rpi4-drm-dunfell-latest/raspberrypi4-64/tmp/work/aarch64-poky-linux/webthings-gateway/1.0.0+gitAUTOINC+4c600fc973-r0/git/node_modules/gifsicle
[13701](https://github.com/meta-flutter/meta-flutter/runs/6017384947?check_suite_focus=true#step:10:13701)
| npm info lifecycle gifsicle@5.1.0~postinstall: Failed to exec postinstall script
[13702](https://github.com/meta-flutter/meta-flutter/runs/6017384947?check_suite_focus=true#step:10:13702)
| npm info lifecycle Error: gifsicle@5.1.0 postinstall: `node lib/install.js`
[13703](https://github.com/meta-flutter/meta-flutter/runs/6017384947?check_suite_focus=true#step:10:13703)
| npm info lifecycle Exit status 1
[13704](https://github.com/meta-flutter/meta-flutter/runs/6017384947?check_suite_focus=true#step:10:13704)
| npm info lifecycle     at EventEmitter.<anonymous> (/__w/meta-flutter/rpi4-drm-dunfell-latest/raspberrypi4-64/tmp/work/aarch64-poky-linux/webthings-gateway/1.0.0+gitAUTOINC+4c600fc973-r0/recipe-sysroot-native/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
[13705](https://github.com/meta-flutter/meta-flutter/runs/6017384947?check_suite_focus=true#step:10:13705)
| npm info lifecycle     at EventEmitter.emit (events.js:314:20)
[13706](https://github.com/meta-flutter/meta-flutter/runs/6017384947?check_suite_focus=true#step:10:13706)
| npm info lifecycle     at ChildProcess.<anonymous> (/__w/meta-flutter/rpi4-drm-dunfell-latest/raspberrypi4-64/tmp/work/aarch64-poky-linux/webthings-gateway/1.0.0+gitAUTOINC+4c600fc973-r0/recipe-sysroot-native/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
[13707](https://github.com/meta-flutter/meta-flutter/runs/6017384947?check_suite_focus=true#step:10:13707)
| npm info lifecycle     at ChildProcess.emit (events.js:314:20)
[13708](https://github.com/meta-flutter/meta-flutter/runs/6017384947?check_suite_focus=true#step:10:13708)
| npm info lifecycle     at maybeClose (internal/child_process.js:1022:16)
[13709](https://github.com/meta-flutter/meta-flutter/runs/6017384947?check_suite_focus=true#step:10:13709)
| npm info lifecycle     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
[13710](https://github.com/meta-flutter/meta-flutter/runs/6017384947?check_suite_focus=true#step:10:13710)
| npm info lifecycle  gifsicle@5.1.0~postinstall: forced, continuing Error: gifsicle@5.1.0 postinstall: `node lib/install.js`
[13711](https://github.com/meta-flutter/meta-flutter/runs/6017384947?check_suite_focus=true#step:10:13711)
| npm info lifecycle Exit status 1
[13712](https://github.com/meta-flutter/meta-flutter/runs/6017384947?check_suite_focus=true#step:10:13712)
| npm info lifecycle     at EventEmitter.<anonymous> (/__w/meta-flutter/rpi4-drm-dunfell-latest/raspberrypi4-64/tmp/work/aarch64-poky-linux/webthings-gateway/1.0.0+gitAUTOINC+4c600fc973-r0/recipe-sysroot-native/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
[13713](https://github.com/meta-flutter/meta-flutter/runs/6017384947?check_suite_focus=true#step:10:13713)
| npm info lifecycle     at EventEmitter.emit (events.js:314:20)
[13714](https://github.com/meta-flutter/meta-flutter/runs/6017384947?check_suite_focus=true#step:10:13714)
| npm info lifecycle     at ChildProcess.<anonymous> (/__w/meta-flutter/rpi4-drm-dunfell-latest/raspberrypi4-64/tmp/work/aarch64-poky-linux/webthings-gateway/1.0.0+gitAUTOINC+4c600fc973-r0/recipe-sysroot-native/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
[13715](https://github.com/meta-flutter/meta-flutter/runs/6017384947?check_suite_focus=true#step:10:13715)
| npm info lifecycle     at ChildProcess.emit (events.js:314:20)
[13716](https://github.com/meta-flutter/meta-flutter/runs/6017384947?check_suite_focus=true#step:10:13716)
| npm info lifecycle     at maybeClose (internal/child_process.js:1022:16)
[13717](https://github.com/meta-flutter/meta-flutter/runs/6017384947?check_suite_focus=true#step:10:13717)
| npm info lifecycle     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5) {
[13718](https://github.com/meta-flutter/meta-flutter/runs/6017384947?check_suite_focus=true#step:10:13718)
| npm info lifecycle   errno: 1,
[13719](https://github.com/meta-flutter/meta-flutter/runs/6017384947?check_suite_focus=true#step:10:13719)
| npm info lifecycle   code: 'ELIFECYCLE',
[13720](https://github.com/meta-flutter/meta-flutter/runs/6017384947?check_suite_focus=true#step:10:13720)
| npm info lifecycle   pkgid: 'gifsicle@5.1.0',
[13721](https://github.com/meta-flutter/meta-flutter/runs/6017384947?check_suite_focus=true#step:10:13721)
| npm info lifecycle   stage: 'postinstall',
[13722](https://github.com/meta-flutter/meta-flutter/runs/6017384947?check_suite_focus=true#step:10:13722)
| npm info lifecycle   script: 'node lib/install.js',
[13723](https://github.com/meta-flutter/meta-flutter/runs/6017384947?check_suite_focus=true#step:10:13723)
| npm info lifecycle   pkgname: 'gifsicle'
[13724](https://github.com/meta-flutter/meta-flutter/runs/6017384947?check_suite_focus=true#step:10:13724)
| npm info lifecycle }
```
