### ISSUE TITLE
Impossible to install behind proxy

### ISSUE THREAD

**Issue by jscti** [imagemin/gifsicle-bin#25]
Hi

I'm trying to install this npm package but it fails. This is the only node package of my app that failed. I set up my .npmrc proxy settings well, all of my others packages are OK

=> reinstalled node and NPM to latest version without success
=> I tried all url found in index.js to see If my proxy rejects it, but all works fine.
edit: in fact, it's the whole grunt-contrib-imagemin dependancies which are KO :
- gifsicle
- jpegtran-bin
- optipng-bin

Thanks

Log report : 

```
λ npm install gifsicle

npm http GET https://registry.npmjs.org/gifsicle
npm http 304 https://registry.npmjs.org/gifsicle
npm http GET https://registry.npmjs.org/bin-wrapper
npm http GET https://registry.npmjs.org/chalk
npm http 304 https://registry.npmjs.org/chalk
npm http 304 https://registry.npmjs.org/bin-wrapper
npm http GET https://registry.npmjs.org/ansi-styles
npm http GET https://registry.npmjs.org/has-color
npm http GET https://registry.npmjs.org/strip-ansi
npm http GET https://registry.npmjs.org/bin-check
npm http GET https://registry.npmjs.org/find-file
npm http GET https://registry.npmjs.org/executable
npm http GET https://registry.npmjs.org/mout
npm http GET https://registry.npmjs.org/progress
npm http GET https://registry.npmjs.org/download
npm http GET https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/tempfile
npm http 304 https://registry.npmjs.org/tempfile
npm http 304 https://registry.npmjs.org/ansi-styles
npm http 304 https://registry.npmjs.org/bin-check
npm http 304 https://registry.npmjs.org/executable
npm http 304 https://registry.npmjs.org/find-file
npm http 304 https://registry.npmjs.org/mout
npm http 304 https://registry.npmjs.org/strip-ansi
npm http 304 https://registry.npmjs.org/progress
npm http 304 https://registry.npmjs.org/has-color
npm http 304 https://registry.npmjs.org/download
npm http 304 https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/uuid
npm http GET https://registry.npmjs.org/each-async
npm http GET https://registry.npmjs.org/decompress
npm http GET https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/request
npm http GET https://registry.npmjs.org/through2
npm http 304 https://registry.npmjs.org/each-async
npm http 304 https://registry.npmjs.org/uuid
npm http 304 https://registry.npmjs.org/through2
npm http 304 https://registry.npmjs.org/mkdirp
npm http 304 https://registry.npmjs.org/decompress
npm http 304 https://registry.npmjs.org/request
npm http GET https://registry.npmjs.org/adm-zip
npm http GET https://registry.npmjs.org/stream-combiner
npm http GET https://registry.npmjs.org/tar
npm http GET https://registry.npmjs.org/readable-stream
npm http GET https://registry.npmjs.org/xtend
npm http GET https://registry.npmjs.org/qs
npm http GET https://registry.npmjs.org/forever-agent
npm http GET https://registry.npmjs.org/node-uuid
npm http GET https://registry.npmjs.org/json-stringify-safe
npm http GET https://registry.npmjs.org/mime
npm http GET https://registry.npmjs.org/tough-cookie
npm http GET https://registry.npmjs.org/form-data
npm http GET https://registry.npmjs.org/http-signature
npm http GET https://registry.npmjs.org/oauth-sign
npm http GET https://registry.npmjs.org/tunnel-agent
npm http GET https://registry.npmjs.org/aws-sign2
npm http GET https://registry.npmjs.org/hawk
npm http 304 https://registry.npmjs.org/readable-stream
npm http 304 https://registry.npmjs.org/stream-combiner
npm http 304 https://registry.npmjs.org/tar
npm http 304 https://registry.npmjs.org/tunnel-agent
npm http 304 https://registry.npmjs.org/xtend
npm http 304 https://registry.npmjs.org/forever-agent
npm http 304 https://registry.npmjs.org/mime
npm http 304 https://registry.npmjs.org/adm-zip
npm http 304 https://registry.npmjs.org/json-stringify-safe
npm http 304 https://registry.npmjs.org/http-signature
npm http 304 https://registry.npmjs.org/aws-sign2
npm http 304 https://registry.npmjs.org/oauth-sign
npm http 304 https://registry.npmjs.org/qs
npm http 304 https://registry.npmjs.org/node-uuid
npm http GET https://registry.npmjs.org/object-keys
npm http GET https://registry.npmjs.org/duplexer
npm http GET https://registry.npmjs.org/string_decoder
npm http 304 https://registry.npmjs.org/form-data
npm http GET https://registry.npmjs.org/inherits
npm http GET https://registry.npmjs.org/block-stream
npm http GET https://registry.npmjs.org/fstream
npm http 304 https://registry.npmjs.org/hawk
npm http 304 https://registry.npmjs.org/tough-cookie
npm http GET https://registry.npmjs.org/combined-stream
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/assert-plus/0.1.2
npm http GET https://registry.npmjs.org/asn1/0.1.11
npm http GET https://registry.npmjs.org/ctype/0.5.2
npm http GET https://registry.npmjs.org/punycode
npm http GET https://registry.npmjs.org/hoek
npm http GET https://registry.npmjs.org/cryptiles
npm http GET https://registry.npmjs.org/boom
npm http GET https://registry.npmjs.org/sntp
npm http 304 https://registry.npmjs.org/string_decoder
npm http 304 https://registry.npmjs.org/object-keys
npm http 304 https://registry.npmjs.org/duplexer
npm http 304 https://registry.npmjs.org/block-stream
npm http 304 https://registry.npmjs.org/fstream
npm http 304 https://registry.npmjs.org/inherits
npm http GET https://registry.npmjs.org/graceful-fs
npm http 304 https://registry.npmjs.org/asn1/0.1.11
npm http 304 https://registry.npmjs.org/assert-plus/0.1.2
npm http 304 https://registry.npmjs.org/ctype/0.5.2
npm http 304 https://registry.npmjs.org/combined-stream
npm http 304 https://registry.npmjs.org/boom
npm http 304 https://registry.npmjs.org/punycode
npm http 304 https://registry.npmjs.org/async
npm http 304 https://registry.npmjs.org/cryptiles
npm http GET https://registry.npmjs.org/delayed-stream/0.0.5
npm http 304 https://registry.npmjs.org/sntp
npm http 304 https://registry.npmjs.org/hoek
npm http 304 https://registry.npmjs.org/graceful-fs
npm http 304 https://registry.npmjs.org/delayed-stream/0.0.5

> gifsicle@0.1.5 postinstall D:\app\node_modules\gifsicle
> node index.js


events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
npm ERR! gifsicle@0.1.5 postinstall: `node index.js`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the gifsicle@0.1.5 postinstall script.
npm ERR! This is most likely a problem with the gifsicle package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls gifsicle
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "D:\\Utilisateurs\\xble769\\_Softs\\\\node.exe" "D:\\Utilisateurs\\xble769\\_Softs\\node_modules\\npm\\bin\\npm-cli.js" "install" "gifsicle" npm ERR! cwd D:\app
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.6
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     D:\app\npm-debug.log
npm ERR! not ok code 0
```

**Comment by sinedied** [comment]
As of today, it's still not fixed.
imagemin is the only package that's having proxy issues in my setup, and it's the same as @bixibu: it tries to build the binary dependencies because it could not download the binary...
