### ISSUE TITLE
Compile vendor gifsicle statically

### ISSUE THREAD

**Issue by offlinehacker** [imagemin/gifsicle-bin#27]
Dynamically compiled binaries don't tend to work well across systems. I can provide you with automatic continous compiled static binaries for different platforms(except sunos), from our package manager, if you want :)

**Comment by thasmo** [comment]
@offlinehacker offline? ;)

**Comment by denji** [comment]
imagemin-gifsicle@5.1.0 -> gifsicle@3.0.3

##### Stable version not building *BSD

```
Module build failed: Error: spawn … node_modules/gifsicle/vendor/gifsicle ENOENT
    at exports._errnoException (util.js:953:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by mathieu-aubin** [comment]
ping @offlinehacker

**Comment by 1yzz** [comment]
5 years later
