### ISSUE TITLE
warning and error with 3.0.1

### ISSUE THREAD

**Issue by oliviertassinari** [imagemin/gifsicle-bin#51]
when npm install imagemin I have the following warning
```
npm WARN cannot run in wd gifsicle@3.0.1 node lib/install.js (wd=/pipeline/source/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle)
```
Then when I'm using image-webpack-loader I have this error

```
    ERROR in ./app/assets/img/choices-logo.gif
    Module build failed: Error: spawn /pipeline/source/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/vendor/gifsicle ENOENT
        at exports._errnoException (util.js:746:11)
        at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
        at child_process.js:1144:20
        at process._tickCallback (node.js:355:11)
     @ ./app/assets/jsx/pages/nhschoices.jsx 46:41-72
```

I'm using node 0.12.7 and npm 2.13.3.

May be linked to https://github.com/npm/npm/issues/8982

**Comment by SerDIDG** [comment]
I fix similar problem just updating npm:
sudo npm install npm -g
