### ISSUE TITLE
NPM 3 Install Fails

### ISSUE THREAD

**Issue by gravidThoughts** [imagemin/gifsicle-bin#52]
node v4.1.2
npm 
Windows 7 Enterprise

```
> gifsicle@3.0.1 postinstall C:\dev\Angular Testing\node_modules\gifsicle
> node lib/install.js

  ‼ Redirected 10 times. Aborting.
  ‼ gifsicle pre-build test failed
  i compiling from source
  x Error: autoreconf -ivf && ./configure --disable-gifview --disable-gifdiff --
prefix="C:\dev\Angular Testing\node_modules\gifsicle\vendor" --bindir="C:\dev\An
gular Testing\node_modules\gifsicle\vendor" && make install
Command failed: C:\WINDOWS\system32\cmd.exe /s /c "autoreconf -ivf"
'autoreconf' is not recognized as an internal or external command,
operable program or batch file.

    at ChildProcess.exithandler (child_process.js:203:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

Appears that it fails to download the binary, and attempts to build it locally. Windows does not have `autoreconf`.

**Comment by shinnn** [comment]
Fixed in https://github.com/imagemin/gifsicle-bin/commit/046ee0e25cc9002a24d9fb230172466aabb20721.
