### ISSUE TITLE
npm install in linux installs with errors

### ISSUE THREAD

**Issue by bmccallister** [imagemin/gifsicle-bin#53]
Performing an npm install gives the following output:
npm install gifsicle
> gifsicle@3.0.1 postinstall ./client/node_modules/gifsicle
> node lib/install.js

  ⚠ Invalid non-string/buffer chunk
  ⚠ gifsicle pre-build test failed
  ℹ compiling from source
  ✖ TypeError: Invalid non-string/buffer chunk
    at chunkInvalid (./client/node_modules/gifsicle/node_modules/bin-build/node_modules/decompress/node_modules/stream-combiner2/node_modules/readable-stream/lib/_stream_readable.js:421:10)
    at readableAddChunk (./client/node_modules/gifsicle/node_modules/bin-build/node_modules/decompress/node_modules/stream-combiner2/node_modules/readable-stream/lib/_stream_readable.js:176:12)
    at DuplexWrapper.Readable.push (./client/node_modules/gifsicle/node_modules/bin-build/node_modules/decompress/node_modules/stream-combiner2/node_modules/readable-stream/lib/_stream_readable.js:162:10)
    at DuplexWrapper._forwardRead (./client/node_modules/gifsicle/node_modules/bin-build/node_modules/decompress/node_modules/stream-combiner2/node_modules/duplexer2/index.js:95:10)
    at DestroyableTransform.<anonymous> (./client/node_modules/gifsicle/node_modules/bin-build/node_modules/decompress/node_modules/stream-combiner2/node_modules/duplexer2/index.js:54:10)
    at DestroyableTransform.emit (events.js:92:17)
    at emitReadable_ (./client/node_modules/gifsicle/node_modules/bin-build/node_modules/decompress/node_modules/decompress-unzip/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:460:10)
    at emitReadable (./client/node_modules/gifsicle/node_modules/bin-build/node_modules/decompress/node_modules/decompress-unzip/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:454:7)
    at readableAddChunk (./client/node_modules/gifsicle/node_modules/bin-build/node_modules/decompress/node_modules/decompress-unzip/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:209:11)
    at DestroyableTransform.Readable.push (./client/node_modules/gifsicle/node_modules/bin-build/node_modules/decompress/node_modules/decompress-unzip/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:162:10)
gifsicle@3.0.1 node_modules/gifsicle
├── logalot@2.1.0 (figures@1.4.0, squeak@1.2.1)
├── bin-build@2.1.2 (exec-series@1.0.2, url-regex@2.1.3, tempfile@1.1.1, rimraf@2.4.3, archive-type@2.1.0, download@4.3.0, decompress@2.3.0)
└── bin-wrapper@3.0.2 (os-filter-obj@1.0.3, lazy-req@1.1.0, each-async@1.1.1, bin-check@2.0.0, bin-version-check@2.1.0, download@4.3.0)

**Comment by rymndhng** [comment]
I saw this myself. I don't want to install from source. The binary URLs all return 301s.

For example on Linux, according to https://github.com/imagemin/gifsicle-bin/blob/master/lib/index.js, the generated URL should be `https://raw.github.com/imagemin/gifsicle-bin/3.0.1/vendor/linux/x64/gifsicle`

```
curl -I  https://raw.github.com/imagemin/gifsicle-bin/3.0.1/vendor/linux/x64/gifsicle
HTTP/1.1 301 Moved Permanently
Location: https://raw.githubusercontent.com/imagemin/gifsicle-bin/3.0.1/vendor/linux/x64/gifsicle
Content-Length: 0
Accept-Ranges: bytes
Date: Sat, 17 Oct 2015 00:45:12 GMT
Via: 1.1 varnish
Age: 0
Connection: keep-alive
X-Served-By: cache-jfk1020-JFK
X-Cache: MISS
X-Cache-Hits: 0
Vary: Accept-Encoding
```

A 301 is returned, with the correct URL.

**Comment by shinnn** [comment]
Fixed in https://github.com/kevva/decompress/commit/b37729eacd0b39ac803eef2a6ca5d53adafb4057.
