### ISSUE TITLE
Error: spawn EPERM when installing gifsicle

### ISSUE THREAD

**Issue by RicoVorihery** [imagemin/gifsicle-bin#66]
Good day,
can someone help me about this error please?
![capture](https://cloud.githubusercontent.com/assets/13149180/19340070/b0ae9e22-912f-11e6-8a2d-fe7b07cc6d2f.JPG)

**Comment by ekryski** [comment]
I'm seeing a similar error on OSX and Linux. Looks like for some reason `node lib/install.js` isn't working.

```
npm install imagemin-gifsicle
npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolchain, use it instead!

> gifsicle@3.0.4 postinstall /Users/eric/Desktop/test/node_modules/gifsicle
> node lib/install.js

module.js:457
    throw err;
    ^

Error: Cannot find module './src/init'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/eric/Desktop/test/node_modules/gulp-sourcemaps/index.js:4:9)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
```

**Comment by jasonm** [comment]
I bet this is the same as https://github.com/imagemin/pngquant-bin/issues/53 and related to https://www.npmjs.com/package/gulp-sourcemaps "published an hour ago"

**Comment by jasonm** [comment]
I think this is upstream https://github.com/floridoo/gulp-sourcemaps/issues/238

**Comment by ekryski** [comment]
Yup it's looking like it. Thanks @jasonm

**Comment by jasonm** [comment]
Verified that adding `+    "gulp-sourcemaps": "1.7.1",` to package.json fixes the issue for me

**Comment by eddiemonge** [comment]
All the comments after the first are for something different than the OP

**Comment by jasonm** [comment]
@eddiemonge is right, I misread.  @ekryski and I share an issue but it appears to be different from this.

**Comment by alex87** [comment]
hi @RicoVorihery I am having a similar issue to you, did you find a work around or fix?

**Comment by majabee** [comment]
I have the same problem gifsicle@3.0.4, jpegtran-bin@3.2.0, pngquant-bin@3.1.1 throw errors in installation process. Couldn't execute the ... binary. Make sure it has the right permissions.

**Comment by xinjingfen** [comment]
I have the same problem!
