### ISSUE TITLE
Error: autoreconf -ivf 

### ISSUE THREAD

**Issue by meness** [imagemin/gifsicle-bin#79]
Hi,

I'm using the latest stable version of NPM and getting following error after `npm install`.

> × Error: autoreconf -ivf && ./configure --disable-gifview --disable-gifdiff --prefix="xxx\node_modules\gifsicle\vendor" --bindir=
> "xxx\node_modules\gifsicle\vendor" && make install
> Command failed: autoreconf -ivf
> 'autoreconf' is not recognized as an internal or external command,
> operable program or batch file.
> 
>     at ChildProcess.exithandler (child_process.js:211:12)
>     at emitTwo (events.js:106:13)
>     at ChildProcess.emit (events.js:192:7)
>     at maybeClose (internal/child_process.js:890:16)
>     at Socket.<anonymous> (internal/child_process.js:334:11)
>     at emitOne (events.js:96:13)
>     at Socket.emit (events.js:189:7)
>     at Pipe._handle.close [as _onclose] (net.js:501:12)
>

**Comment by nwaweru** [comment]
Linux:
    sudo apt-get install libtool automake autoconf nasm
OS X:
    brew install libtool automake autoconf nasm

**Comment by KeithCowan** [comment]
How about on Windows??

**Comment by mojavelinux** [comment]
The update to 4.0.1 broken installation on Alpine Linux.

```
Output:
⚠ spawn /root/node_modules/gifsicle/vendor/gifsicle ENOENT
  ⚠ gifsicle pre-build test failed
  ℹ compiling from source
  ✖ Error: Command failed: /bin/sh -c autoreconf -ivf
/bin/sh: autoreconf: not found
```

**Comment by zzroche** [comment]
> 
> 
> How about on Windows??

I've the same problem

**Comment by gsaini** [comment]
I also have the same issue on windows machine.

**Comment by zzroche** [comment]
Also doesn't work without gulp.

**Comment by lukas-lansky** [comment]
> Linux:
> `sudo apt-get install libtool automake autoconf nasm`

In Alpine, `apk add libtool automake autoconf nasm` is not sufficient as it leads to `configure: error: no acceptable C compiler found in $PATH`. `apk add build-base` helped me with this problem, but that for itself says `OK: 271 MiB in 52 packages`. It really forces staged builds.

**Comment by RainLucky** [comment]
> 我在Windows机器上也有同样
我也是，请问你们这个问题解决了吗?
Me too.Have you solved this problem?

**Comment by Pines-Cheng** [comment]
> Linux:
> `sudo apt-get install libtool automake autoconf nasm`
> OS X:
> `brew install libtool automake autoconf nasm`

fixed my problem.

**Comment by EmanueleCiriachi** [comment]
I'm on Windows. As per [this comment](https://github.com/imagemin/imagemin-gifsicle/issues/33#issuecomment-640211831), adding the following entries to the hosts file temporarily solved the problem for me:

`2.74.223.119     github.com
192.30.253.119    gist.github.com
54.169.195.247    api.github.com
185.199.111.153   assets-cdn.github.com
151.101.76.133    raw.githubusercontent.com
151.101.76.133    gist.githubusercontent.com
151.101.76.133    cloud.githubusercontent.com
151.101.76.133    camo.githubusercontent.com
151.101.76.133    avatars0.githubusercontent.com
151.101.76.133    avatars1.githubusercontent.com
151.101.76.133    avatars2.githubusercontent.com
151.101.76.133    avatars3.githubusercontent.com
151.101.76.133    avatars4.githubusercontent.com
151.101.76.133    avatars5.githubusercontent.com
151.101.76.133    avatars6.githubusercontent.com
151.101.76.133    avatars7.githubusercontent.com
151.101.76.133    avatars8.githubusercontent.com`

**Comment by norhan22** [comment]
> I'm on Windows. As per [this comment](https://github.com/imagemin/imagemin-gifsicle/issues/33#issuecomment-640211831), adding the following entries to the hosts file temporarily solved the problem for me:
> 
> `2.74.223.119 github.com`
> `192.30.253.119 gist.github.com`
> `54.169.195.247 api.github.com`
> `185.199.111.153 assets-cdn.github.com`
> `151.101.76.133 raw.githubusercontent.com`
> `151.101.76.133 gist.githubusercontent.com`
> `151.101.76.133 cloud.githubusercontent.com`
> `151.101.76.133 camo.githubusercontent.com`
> `151.101.76.133 avatars0.githubusercontent.com`
> `151.101.76.133 avatars1.githubusercontent.com`
> `151.101.76.133 avatars2.githubusercontent.com`
> `151.101.76.133 avatars3.githubusercontent.com`
> `151.101.76.133 avatars4.githubusercontent.com`
> `151.101.76.133 avatars5.githubusercontent.com`
> `151.101.76.133 avatars6.githubusercontent.com`
> `151.101.76.133 avatars7.githubusercontent.com`
> `151.101.76.133 avatars8.githubusercontent.com`

Where should I add this lines ?
 I have the same error

**Comment by EmanueleCiriachi** [comment]
> Where should I add this lines ?
> I have the same error

In the hosts file.

**Comment by lhtdesignde** [comment]
Just ran into this issue with version 5.1.0. Locally it seem fine. However running with circle ci i get the error:
<img width="481" alt="Screenshot 2020-08-27 at 13 43 06" src="https://user-images.githubusercontent.com/5528640/91438320-7036b680-e86b-11ea-8035-de599fe35f63.png">
```
Error: Command failed: /bin/sh -c autoreconf -ivf
/bin/sh: 1: autoreconf: not found
```
Any workaround yet?

**Comment by sbddesign** [comment]
> Just ran into this issue with version 5.1.0. Locally it seem fine. However running with circle ci i get the error:
> <img alt="Screenshot 2020-08-27 at 13 43 06" width="481" src="https://user-images.githubusercontent.com/5528640/91438320-7036b680-e86b-11ea-8035-de599fe35f63.png">
> 
> ```
> Error: Command failed: /bin/sh -c autoreconf -ivf
> /bin/sh: 1: autoreconf: not found
> ```
> 
> Any workaround yet?

@lhtdesignde I had the same error message in Ubuntu 20.04. I solved the problem by running `sudo apt-get install autoconf
`.

I am not very experienced with Circle CI, but perhaps there a way to configure it to install `autoconf` prior to running `npm install`? For example, I sometimes uses Docker for development, and with that you can setup your Dockerfile to run CLI commands and install different types of dependencies in a specific order.

**Comment by wenjq2018** [comment]
I have the same on Win

**Comment by HugoPrunaux** [comment]
Not sure if that will help future users on Windows, but for me, the issue was that I was behind a corporate proxy. Disabling it solved the issue and the pre-build test passed successfully.
