### ISSUE TITLE
Module build failed: ModuleBuildError: Module build failed: Error: spawn  ENOENT

### ISSUE THREAD

**Issue by IAMtheIAM** [imagemin/gifsicle-bin#83]
Using webpack, Build fails inside a `docker-node` container running linux alpine. Build works fine under windows.
```
ERROR in ./node_modules/lightgallery.js/src/sass/lightgallery.scss
Module build failed: ModuleBuildError: Module build failed: Error: spawn /home/node/app/frontend/node_modules/gifsicle/vendor/gifsicle ENOENT
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at runLoaders (/home/node/app/frontend/node_modules/webpack/lib/NormalModule.js:195:19)
    at /home/node/app/frontend/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /home/node/app/frontend/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at context.callback (/home/node/app/frontend/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at imagemin.buffer.then.catch.err (/home/node/app/frontend/node_modules/image-webpack-loader/index.js:92:9)
    at <anonymous>
 @ ./src/app-components/+listing/listing/listing.component.ts 27:0-53
 @ ./src/app-components/+listing/listing.module.ngfactory.js
 @ ./$$_lazy_route_resource lazy
 @ ./node_modules/@angular/core/esm5/core.js
 @ ./src/vendors.ts
```
`/node_modules/gifsicle/vendor/gifsicle` this binary exists so I don't know what it says is ENOENT

**Comment by yuriybabenko** [comment]
Did you ever resolve this? I'm getting the same problem on Ubuntu.

**Comment by yuriybabenko** [comment]
Seems that running `npm install` in the `node_modules/gifsicle` directory did the trick.

**Comment by IAMtheIAM** [comment]
Not sure, but I'm closing this since it's been resolved for me. Likely a corrupt node_modules folder so wiping that and `npm install`ing should work
